version: '3.2'
services:
  web:
    build: .
    ports:
      - '4000:4000'
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/app:cached
      - /app/.git
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: {}
